/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as PrediosRouteImport } from './routes/predios'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as PredioPredioIdRouteImport } from './routes/predio.$predioId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const PrediosRoute = PrediosRouteImport.update({
  id: '/predios',
  path: '/predios',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const PredioPredioIdRoute = PredioPredioIdRouteImport.update({
  id: '/predio/$predioId',
  path: '/predio/$predioId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/predios': typeof PrediosRoute
  '/reportes': typeof ReportesRoute
  '/predio/$predioId': typeof PredioPredioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/predios': typeof PrediosRoute
  '/reportes': typeof ReportesRoute
  '/predio/$predioId': typeof PredioPredioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/predios': typeof PrediosRoute
  '/reportes': typeof ReportesRoute
  '/predio/$predioId': typeof PredioPredioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/configuracion'
    | '/predios'
    | '/reportes'
    | '/predio/$predioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/configuracion'
    | '/predios'
    | '/reportes'
    | '/predio/$predioId'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/configuracion'
    | '/predios'
    | '/reportes'
    | '/predio/$predioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  PrediosRoute: typeof PrediosRoute
  ReportesRoute: typeof ReportesRoute
  PredioPredioIdRoute: typeof PredioPredioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predios': {
      id: '/predios'
      path: '/predios'
      fullPath: '/predios'
      preLoaderRoute: typeof PrediosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predio/$predioId': {
      id: '/predio/$predioId'
      path: '/predio/$predioId'
      fullPath: '/predio/$predioId'
      preLoaderRoute: typeof PredioPredioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  PrediosRoute: PrediosRoute,
  ReportesRoute: ReportesRoute,
  PredioPredioIdRoute: PredioPredioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
